# Site settings
title: Naren Surampudi
description: A portfolio of Naren's Work
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Naren Surampudi
user_description: I am an undergrad at BITS Pilani-Hyderabad Campus, and an aspiring software developer.
user_title: Aspiring Software Developer
email: nsurampu@gmail.com
github_username:  nsurampu
linkedin: naren-surampudi/


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
