# Site settings
title: Mayank Gupta
description: A portfolio of Mayank's Work
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mayank Gupta
user_description: A dual degree holding with strong passion for all things Bio related. I am passionate about Social entrepreneurship. In my free time, I immerse myself in reading, music-especiaaly Carnatic music, gaming and playing the tabla.
user_title: Aspiring Business Analytics
email: mayankguptaino@gmail.com
github_username:  Oce11us
linkedin: mayank-gupta-35bb69125/


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
